services:
  redis:
    image: redis:latest
    container_name: sarafrika-redis
    command: redis-server --appendonly yes --requirepass $${REDIS_PASSWORD:-redis123}
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - sarafrika-network
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "$${REDIS_PASSWORD:-redis123}", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  app:
    image: sarafrika/sarafrika-camp-ussd:latest
    container_name: camp-ussd
    env_file:
      - .env
    ports:
      - "40000:8080"
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - sarafrika-network
    restart: unless-stopped

volumes:
  redis_data:
    driver: local

networks:
  sarafrika-network:
    driver: bridge