quarkus:
  application:
    name: sarafrika-camp-ussd
    
  datasource:
    db-kind: postgresql
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    jdbc:
      url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:sarafrika_camp}
      
  hibernate-orm:
    database:
      generation: none
    log:
      sql: false
    mapping:
      format:
        global: ignore
      
  flyway:
    migrate-at-start: true
    baseline-on-migrate: true
    
  redis:
    hosts: redis://${REDIS_HOST:localhost}:${REDIS_PORT:6379}
    timeout: 10s
    
  rest-client:
    celcom-africa:
      url: https://isms.celcomafrica.com
    cheddar-api:
      url: https://cheddar.sarafrika.com
      
  smallrye-openapi:
    path: /openapi
    
  swagger-ui:
    always-include: true
    path: /swagger-ui
    
  http:
    port: 8080

celcom-africa:
  api-key: ${CELCOM_API_KEY:f08988cfb329fc8c66c2bc44d8f7fc10}
  partner-id: ${CELCOM_PARTNER_ID:862}
  shortcode: ${CELCOM_SHORTCODE:Sarafrika}

cheddar:
  paybill: ${CHEDDAR_PAYBILL:4953892}
  callback-url: https://camp-ussd.sarafrika.com/api/payments/confirm
  
ussd:
  service-code: ${USSD_SERVICE_CODE:*789*2020#}
  session-timeout: 300 # 5 minutes in seconds

app:
  organizer-contact: ${ORGANIZER_CONTACT:0712-345678}

logging:
  level:
    apps.sarafrika: DEBUG